In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,4])

euc_dis = np.sqrt(np.dot(b-a, b-a))
print(euc_dis)

4.358898943540674


In [2]:
euc_dis = np.linalg.norm(b - a)
print(euc_dis)

4.358898943540674


In [3]:
# 
X = np.array([[1,2], [2,3], [3,4], [4,5], [5,6]])
print(X)

cluster_group = np.array([1,0,0,0,1])

print(np.unique(cluster_group))


[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]]
[0 1]


In [4]:
print(f"New centroids: {X[cluster_group==0].mean(axis = 0)}")
print(f"New centroids: {X[cluster_group==1].mean(axis = 0)}")

for type in np.unique(cluster_group):
    print(X[cluster_group==type].mean(axis = 0))


New centroids: [3. 4.]
New centroids: [3. 4.]
[3. 4.]
[3. 4.]


In [11]:
import random
random_index = random.sample(range(0, X.shape[0]), 2)
centroids = X[random_index]

print(X)
print("Random Index are \n")
print(random_index)
centroids

[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]]
Random Index are 

[0, 2]


array([[1, 2],
       [3, 4]])

In [14]:
X = np.array([[1,2], [2,3], [3,4], [4,5], [5,6], [2,2], [3,3], [1,4], [4,6], [5,1], [1,3], [1,3], [3,3], [4,1], [5,1]])

In [15]:
cluster_group = [1,1,1,1,0,0,0,0,1,1,1,1,0,0,0]
new_centroids = []
cluster_type = np.unique(cluster_group)
print(cluster_type)
for type in cluster_type:
    new_centroids.append(X[cluster_group==type].mean(axis = 0))

print(new_centroids)

[0 1]
[array([3.28571429, 2.85714286]), array([2.625, 3.375])]


In [20]:
x = np.array([[5,6], [2,2], [3,3]])
x.mean(axis = 0)

array([3.33333333, 3.66666667])

In [28]:
random_idx = random.sample(range(0, X.shape[0]), 2)
centroids = X[random_idx]

In [29]:
centroids

array([[5, 1],
       [3, 3]])

In [31]:
random_idx

[9, 12]